services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: metatrackdb
      POSTGRES_USER: metatrack
      POSTGRES_PASSWORD: metatrack
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: