spring:
  application:
    name: metatrack-api
  threads:
    virtual:
      enabled: true
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: metatrack_api
            client-secret: x5u6y6hEDQiO8i2t7Xc3j6FKs6dWBcgL
            authorization-grant-type: password
            scope: openid, profile, email
            redirect-uri: "http://localhost:8080/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/metatrack
            token-uri: http://localhost:8090/realms/metatrack/protocol/openid-connect/token

minio:
  endpoint: http://localhost:9000
  access-key: minio
  secret-key: password
  bucket: uploads

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

keycloak:
  realm: metatrack
  url: http://localhost:8090
  admin-username: admin
  admin-password: admin