package no.metatrack.api.enums;

public enum TaxonomyRank {

	NO_RANK, SUPERKINGDOM, DOMAIN, REALM, KINGDOM, SUBKINGDOM, SUPERPHYLUM, SUBPHYLUM, PHYLUM, CLADE, SUPERCLASS, CLASS,
	SUBCLASS, INFRACLASS, COHORT, SUBCOHORT, SUPERORDER, ORDER, SUBORDER, INFRAORDER, PARVORDER, SUPERFAMILY, FAMILY,
	SUBFAMILY, GENUS, SUBGENUS, SPECIES_GROUP, SPECIES_SUBGROUP, SPECIES, SUBSPECIES, TRIBE, SUBTRIBE, FORMA, VARIETAS,
	STRAIN, SECTION, SUBSECTION, PATHOGROUP, SUBVARIETY, GENOTYPE, SEROTYPE, ISOLATE, MORPH, SERIES, FORMA_SPECIALIS,
	SEROGROUP, BIOTYPE, ACELLULAR_ROOT, CELLULAR_ROOT

}
