package no.metatrack.api.enums;

public enum TaxonomyCountsType {

	COUNT_TYPE_UNSPECIFIED, COUNT_TYPE_ASSEMBLY, COUNT_TYPE_GENE, COUNT_TYPE_tRNA, COUNT_TYPE_rRNA, COUNT_TYPE_snRNA,
	COUNT_TYPE_scRNA, COUNT_TYPE_snoRNA, COUNT_TYPE_PROTEIN_CODING, COUNT_TYPE_PSEUDO, COUNT_TYPE_TRANSPOSON,
	COUNT_TYPE_miscRNA, COUNT_TYPE_ncRNA, COUNT_TYPE_BIOLOGICAL_REGION, COUNT_TYPE_OTHER, COUNT_TYPE_ORGANELLE

}
