apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: elixir-uit-ns11105k
  labels:
    app: prometheus
    component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'metatrack-api'
        metrics_path: /actuator/prometheus
        scrape_interval: 15s
        static_configs:
          - targets: ['metatrack-service:8090']
