apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: elixir-uit-ns11105k
  labels:
    app: grafana
    component: monitoring
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
        jsonData:
          timeInterval: 15s
